#!/usr/bin/env python3
"""Generate a CRAB config for the unified SmartPixels NanoAOD production.

Produces one CRAB `config` script that runs the L1 NanoAOD tier
(@L1PFTrkNanowithGen -- the fullest nano flavor: L1 tracks + matched-TP truth,
PF/Puppi candidates + jet-constituent links, the NG jet-tagger tier, GenJet
flavor labels, and vertices) with the SmartPixels digiRefit tables for a chosen
SmartPixels config (activeSP, e.g. 1100) layered on top via smartPixelsCoexist.

The emitted CRAB config points at the production pset
  L1Trigger/Phase3SmartPixels/python/runUnifiedNano_cfg.py
and passes it, via pyCfgParams, the parameter CONTRACT below. The pset must
accept these VarParsing('analysis') options:
  activeSP        (string)  SmartPixels active-layer config, e.g. "1100"
  tier            (string)  autoNANO flavor, default "L1PFTrkNanowithGen"
  seedCovMode     (string)  "trackCov" (covMatrix branch) | "parametrized"
  pixelavAngleSet (string)  PixelAV angle-response payload (basename in the CRAB
                            job cwd when shipped via JobType.inputFiles)
CRAB overrides process.source.fileNames from config.Data.inputDataset, so the
pset only needs a valid (placeholder) PoolSource.

DATASET: there is deliberately NO default. Input must be POST-cms-sw/cmssw#51503
(that PR rewrote the persisted L1 track-trigger DataFormats), which rules out the
CMSSW_14/15-era samples the CMSSW_17_0 version of this tooling targeted. The D121
RelVals used for local validation are DBS datasets, but their dataset paths are
not recorded here -- look them up before submitting. Run without --inputDataset
to emit a config with the dataset left blank and a TODO marker.

Example:
  python3 makeCrabUnifiedNano.py --activeSP 1100            # dataset left blank
  python3 makeCrabUnifiedNano.py --activeSP 1100 \
      --inputDataset '/PRIMARY/PROCESSED/GEN-SIM-DIGI-RAW-MINIAOD'
Writes crab_fullnano_<tag>_SP1100_<primary>.py by default.
"""
import argparse
import os
import re
import sys


def sanitize(token):
    """CRAB requestName: <=100 chars, only [A-Za-z0-9_-]."""
    return re.sub(r"[^A-Za-z0-9_-]", "_", token)


DATASET_UNSET = "DATASET_TODO"


def primary_name(dataset):
    """Primary dataset name = first field of /PRIMARY/PROCESSED/TIER.

    An empty dataset is allowed (no post-#51503 dataset exists yet); it yields a
    placeholder primary so the request name is still well-formed."""
    if not dataset:
        return DATASET_UNSET
    parts = [p for p in dataset.split("/") if p]
    if len(parts) < 3:
        raise ValueError(
            "inputDataset must look like /PRIMARY/PROCESSED/TIER, got: %r" % dataset)
    return parts[0]


def build_config(args):
    primary = primary_name(args.inputDataset)
    version_tag = args.outLFNDirBase.rstrip("/").split("/")[-1]  # e.g. "v2p5"

    request = args.requestName or "fullnano_%s_SP%s_%s" % (
        version_tag, args.activeSP, primary)
    request = sanitize(request)
    if len(request) > 100:
        request = request[:100]

    pyparams = [
        "activeSP=%s" % args.activeSP,
        "tier=%s" % args.tier,
        "seedCovMode=%s" % args.seedCovMode,
    ]
    input_files = []
    if args.payload:
        # ship the PixelAV payload into the CRAB sandbox; the pset resolves it by
        # basename in the job cwd.
        input_files.append(args.payload)
        pyparams.append("pixelavAngleSet=%s" % os.path.basename(args.payload))
    input_files += list(args.extraInputFiles or [])

    total_units = ("\nconfig.Data.totalUnits = %d" % args.totalUnits
                   if args.totalUnits else "")

    todo = ([] if args.inputDataset else
            ["# TODO: config.Data.inputDataset is EMPTY -- no post-cms-sw/cmssw#51503",
             "#       dataset exists yet. Fill it in before `crab submit`; a pre-break",
             "#       (CMSSW_14/15-era) sample will NOT read correctly on this branch.",
             ""])

    lines = todo + [
        "# Auto-generated by makeCrabUnifiedNano.py -- unified SmartPixels NanoAOD",
        "#   dataset : %s" % (args.inputDataset or "<UNSET>"),
        "#   activeSP: %s   tier: %s   seedCovMode: %s" % (
            args.activeSP, args.tier, args.seedCovMode),
        "from CRABClient.UserUtilities import config",
        "config = config()",
        "",
        "# General section",
        "config.General.requestName = %r" % request,
        "config.General.workArea = 'crab_projects'",
        "config.General.transferOutputs = True",
        "config.General.transferLogs = True",
        "",
        "# JobType section",
        "config.JobType.pluginName = 'Analysis'",
        "config.JobType.psetName = %r" % args.pset,
        "config.JobType.numCores = %d" % args.numCores,
        "config.JobType.maxMemoryMB = %d" % args.maxMemoryMB,
        "config.JobType.allowUndistributedCMSSW = True",
        "config.JobType.pyCfgParams = %r" % (pyparams,),
        "config.JobType.inputFiles = %r" % (input_files,),
        "",
        "# Data section",
        "config.Data.inputDBS = %r" % args.inputDBS,
        "config.Data.inputDataset = %r" % args.inputDataset,
        "config.Data.splitting = 'FileBased'",
        "config.Data.unitsPerJob = %d" % args.unitsPerJob + total_units,
        "config.Data.outLFNDirBase = %r" % args.outLFNDirBase,
        "config.Data.publication = %s" % bool(args.publication),
        "config.Data.outputDatasetTag = %r" % request,
        "",
        "# Site section",
        "config.Site.storageSite = %r" % args.storageSite,
        "",
    ]
    return request, "\n".join(lines)


def main(argv=None):
    ap = argparse.ArgumentParser(
        description="Generate a CRAB config for unified SmartPixels NanoAOD.")
    ap.add_argument("--inputDataset", default="",
                    help="DBS dataset /PRIMARY/PROCESSED/GEN-SIM-DIGI-RAW-MINIAOD. "
                         "Default empty: no post-#51503 dataset exists yet, so the "
                         "emitted config carries a blank dataset + TODO marker.")
    ap.add_argument("--activeSP", default="1100",
                    help="SmartPixels active-layer config (default: 1100)")
    ap.add_argument("--outLFNDirBase",
                    default="/store/user/lpcsmartpixelscms/fullnano/v2pX",
                    help="output LFN base (default: %(default)s). The trailing "
                         "component is the version tag that lands in the request "
                         "name; it is a PLACEHOLDER (v2pX) until the post-CMSSW_20 "
                         "version increment is decided.")
    ap.add_argument("--tier", default="L1PFTrkNanowithGen",
                    help="autoNANO flavor (default: %(default)s -- fullest)")
    ap.add_argument("--seedCovMode", default="trackCov",
                    choices=["trackCov", "parametrized"],
                    help="digiRefit seed covariance mode (default: trackCov). Use "
                         "trackCov only on the covMatrix build; parametrized otherwise.")
    ap.add_argument("--pset",
                    default="L1Trigger/Phase3SmartPixels/python/runUnifiedNano_cfg.py",
                    help="cmsRun pset path within the CMSSW area (default: %(default)s)")
    ap.add_argument("--payload", default=None,
                    help="PixelAV angle-response JSON to ship in the sandbox "
                         "(config.JobType.inputFiles); pset gets its basename.")
    ap.add_argument("--extraInputFiles", nargs="*", default=None,
                    help="additional files for config.JobType.inputFiles")
    ap.add_argument("--storageSite", default="T3_US_FNALLPC")
    ap.add_argument("--inputDBS", default="global")
    ap.add_argument("--unitsPerJob", type=int, default=1)
    ap.add_argument("--totalUnits", type=int, default=0,
                    help="cap total units (0 = all)")
    ap.add_argument("--numCores", type=int, default=4)
    ap.add_argument("--maxMemoryMB", type=int, default=10000)
    ap.add_argument("--requestName", default=None,
                    help="override the auto request name")
    ap.add_argument("--publication", action="store_true",
                    help="publish the output dataset in DBS (default: off)")
    ap.add_argument("--outfile", default=None,
                    help="output crab config path (default: crab_<requestName>.py)")
    ap.add_argument("--print", dest="to_stdout", action="store_true",
                    help="print to stdout instead of writing a file")
    args = ap.parse_args(argv)

    request, text = build_config(args)
    if not args.inputDataset:
        sys.stderr.write(
            "WARNING: no --inputDataset given; emitted config has a BLANK dataset "
            "and a TODO marker. Fill it in before `crab submit` (and only with a "
            "post-cms-sw/cmssw#51503 sample).\n")
    if args.to_stdout:
        sys.stdout.write(text + "\n")
        return 0
    outfile = args.outfile or ("crab_%s.py" % request)
    with open(outfile, "w") as fh:
        fh.write(text + "\n")
    sys.stderr.write("wrote %s  (requestName=%s)\n" % (outfile, request))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
